
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Dec 28 08:25:02 PST 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POW = 44;
  public static final int QUERY = 31;
  public static final int LBRACKET = 48;
  public static final int CHAR = 65;
  public static final int VECHEAD = 56;
  public static final int READINT = 29;
  public static final int CASE = 23;
  public static final int CAR = 10;
  public static final int INTEGER = 58;
  public static final int SEMI = 52;
  public static final int LPAREN = 46;
  public static final int CDR = 11;
  public static final int PRINTLN = 6;
  public static final int BINFUNC = 7;
  public static final int MINUS = 39;
  public static final int CMP = 19;
  public static final int RCBRACKET = 51;
  public static final int RPAREN = 47;
  public static final int BININT = 60;
  public static final int NOT = 20;
  public static final int AND = 21;
  public static final int FRACTION = 61;
  public static final int IN = 24;
  public static final int OR = 22;
  public static final int COMMA = 53;
  public static final int LAZY = 30;
  public static final int CALL = 12;
  public static final int INC = 38;
  public static final int DIV = 42;
  public static final int PLUS = 37;
  public static final int ASSIGN = 2;
  public static final int IF = 16;
  public static final int DOT = 55;
  public static final int WAIT = 5;
  public static final int EOF = 0;
  public static final int RBRACKET = 49;
  public static final int EQUAL = 45;
  public static final int TRUE = 35;
  public static final int SIZE = 32;
  public static final int error = 1;
  public static final int HEXINT = 59;
  public static final int MOD = 43;
  public static final int PAIR = 9;
  public static final int BINQUERY = 8;
  public static final int CON = 33;
  public static final int REAL = 62;
  public static final int TIMES = 41;
  public static final int EQV = 15;
  public static final int COLON = 54;
  public static final int ELSE = 18;
  public static final int LCBRACKET = 50;
  public static final int BE = 4;
  public static final int READ = 28;
  public static final int LIST = 13;
  public static final int SUBSTR = 14;
  public static final int LET = 3;
  public static final int THEN = 17;
  public static final int VECEND = 57;
  public static final int STRING = 64;
  public static final int PROC = 26;
  public static final int DEF = 25;
  public static final int ELIST = 34;
  public static final int DEC = 40;
  public static final int FALSE = 36;
  public static final int VAR = 63;
  public static final int PRINT = 27;
}

