
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 20 16:18:31 PST 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POW = 31;
  public static final int LBRACKET = 12;
  public static final int CAR = 25;
  public static final int INTEGER = 39;
  public static final int CDR = 26;
  public static final int LPAREN = 10;
  public static final int SEMI = 16;
  public static final int PRINTLN = 23;
  public static final int MINUS = 6;
  public static final int CMP = 35;
  public static final int RCBRACKET = 15;
  public static final int RPAREN = 11;
  public static final int BININT = 41;
  public static final int AND = 37;
  public static final int NOT = 36;
  public static final int FRACTION = 42;
  public static final int OR = 38;
  public static final int IN = 19;
  public static final int COMMA = 17;
  public static final int DIV = 8;
  public static final int PLUS = 5;
  public static final int ASSIGN = 2;
  public static final int IF = 32;
  public static final int WAIT = 4;
  public static final int EOF = 0;
  public static final int RBRACKET = 13;
  public static final int EQUAL = 30;
  public static final int error = 1;
  public static final int HEXINT = 40;
  public static final int MOD = 9;
  public static final int PAIR = 24;
  public static final int REAL = 43;
  public static final int EQV = 29;
  public static final int TIMES = 7;
  public static final int COLON = 18;
  public static final int ELSE = 34;
  public static final int LCBRACKET = 14;
  public static final int LIST = 27;
  public static final int SUBSTR = 28;
  public static final int LET = 3;
  public static final int THEN = 33;
  public static final int STRING = 45;
  public static final int PROC = 21;
  public static final int DEF = 20;
  public static final int VAR = 44;
  public static final int PRINT = 22;
}

